### ISSUE TITLE
Chybejici podukoly

### ISSUE THREAD

**Issue by nomad-cc20** [st58206/ICSHP---programy#1]
https://github.com/st58206/ICSHP---programy/blob/9c1d14ea984a040fecfcddcb3c4d03fcb0b40a25/CV03/BaseLib/Class1.cs#L64

Chybi tridy ExtraMath a MathConvertor (idealne v samostatnych zdrojovych souborech).

**Comment by st58206** [comment]
Ale ty třídy by tam měly být.
BaseLib/BaseLib/Class1.cs
